Unit2
igRock/java-super-course pull request #3
Opened 2020-01-28 08:46 UTC by igRock

2020-01-29 06:14 UTC, vadim-hleif commented on unit2/src/main/java/stationery_app/StationeryApp.java
> +        employee.setWorkingAddress(workPlace.getAddress());
странное решение, почему просто ссылку на workPlace не сетать? 
хотя он тут особо не нужен, хватит и того, что у сотрудник а есть какие-то канцелярские товары

2020-01-29 06:14 UTC, vadim-hleif commented on unit2/src/main/java/stationery_app/company/Employee.java
> +    private static int id;
не очень красивое решение со статик счетчиком + не потокобезопасное 

и зачем тебе вообще ид этот?

2020-01-29 06:14 UTC, vadim-hleif commented on unit2/src/main/java/stationery_app/StationeryApp.java
> +        Collections.sort(stationeries, Comparator.comparing(Stationery::getName).thenComparing(Stationery::getPrice));
<img width="896" alt="image" src="https://user-images.githubusercontent.com/11632146/73332385-64105980-4288-11ea-84f5-22bd240da9d6.png">

у листа и так сорт есть

2020-01-29 06:26 UTC, igRock commented on unit2/src/main/java/stationery_app/company/Employee.java
> +    private static int id;
ну типа табельный номер. Не более того.

2020-01-29 06:27 UTC, igRock commented on unit2/src/main/java/stationery_app/StationeryApp.java
> +        employee.setWorkingAddress(workPlace.getAddress());
да, поправлю

2020-01-29 07:23 UTC, vadim-hleif commented on unit2/src/main/java/stationery_app/company/Employee.java
> +    private static int id;
ну дали, не юзаешь ведь)

2020-01-29 07:24 UTC, vadim-hleif commented on unit2/src/main/java/stationery_app/company/Employee.java
> +    private static int id;
https://ru.wikipedia.org/wiki/YAGNI

2020-01-31 13:43 UTC, vadim-hleif commented
структура норм, только почему у студента может быть одна оценка? сделай лист + при выводе считай среднюю

и группа не должна уметь сам себя печатать в консоль, ооп

группа не должна уметь проставлять оценки студенту (это структура же)
студент тоже не должен уметь печтать свои оценки в консоль

2020-02-01 11:10 UTC, vadim-gleyf requested changes

2020-02-01 11:10 UTC, vadim-hleif commented on unit2/src/main/java/student_groups/StudentGroupsApp.java
> +        studentMarkMap.keySet().forEach(student -> {
entrySet же можно, тогда не надо будет потом по студенту доставать оценки

2020-02-01 11:10 UTC, vadim-hleif commented on unit2/src/main/java/student_groups/Student.java
> +public class Student {
студент у тебя как ключ хешмапы, ничего не забыл?

2020-02-01 11:26 UTC, igRock commented on unit2/src/main/java/student_groups/StudentGroupsApp.java
> +        studentMarkMap.keySet().forEach(student -> {
поправил

2020-02-01 11:27 UTC, igRock commented on unit2/src/main/java/student_groups/Student.java
> +public class Student {
добавил hash и  equals

2020-02-18 17:13 UTC, merged