unit 3-4
igRock/java-super-course pull request #4
Opened 2020-02-18 18:03 UTC by igRock

2020-02-19 10:03 UTC, vadim-gleyf requested changes

2020-02-19 10:03 UTC, vadim-gleyf commented on unit3-4/src/main/java/crazy_logger/CrazyLogger.java
> +    private DateTimeFormatter DATE_FORMAT = DateTimeFormatter.ofPattern("dd.MM.yyyy hh:mm");
name convention

2020-02-19 10:03 UTC, vadim-gleyf commented on unit3-4/src/main/java/crazy_logger/CrazyLogger.java
> +    private DateTimeFormatter DATE_FORMAT = DateTimeFormatter.ofPattern("dd.MM.yyyy hh:mm");
не static же


замечания идея и сонара сам фикси, без моего участия)

2020-02-19 10:03 UTC, vadim-gleyf commented on unit3-4/src/main/java/crazy_logger/CrazyLogger.java
> +    public void printLog() {
через паблик апи не можешь результат поиска получить
типа только в консоль печатать

в идеале лог не должен ничего знать по консоль (ооп)


массив/список возвращать и все, пофиг че там делают дальше

2020-02-19 10:03 UTC, vadim-gleyf commented on unit3-4/src/main/java/crazy_logger/CrazyLogger.java
> +    public void printLog() {
это про 
   public void printLog(String byString) {
   public void printLog(LocalDateTime ldt) {



а   private String getLog(String byString) {

приватный и уже форматированную строку возвращает (именно для твоего кейса вывода в консоль)

2020-02-19 10:03 UTC, vadim-gleyf commented on unit3-4/src/main/java/locale/LoacaleApp.java
> +    public static void main(String[] args) {
Разработать приложение, позволяющее по выбору пользователя использовать русский или английский язык, для отображения информации.  Приложение должно представлять собой перечень вопросов под номерами (на английском или русском соответственно). Выбрав номер вопроса пользователь может узнать ответ на него.

не спрашивает ответ на какой вопрос я хочу

2020-02-19 10:03 UTC, vadim-gleyf commented on unit3-4/src/main/java/java_parsers/Main.java
> +        String basePath = new File("").getAbsolutePath().concat("/unit3-4/src/main/java/java_parsers");
<img width="1210" alt="image" src="https://user-images.githubusercontent.com/11632146/74821413-5dc04b00-5325-11ea-8186-4687fdcd58bc.png">

2020-02-19 10:03 UTC, vadim-gleyf commented on unit3-4/src/main/java/java_parsers/Main.java
> +        String basePath = new File("").getAbsolutePath().concat("/unit3-4/src/main/java/java_parsers");
папку руками создавать надо

2020-02-19 10:03 UTC, vadim-gleyf commented on unit3-4/src/main/java/java_parsers/KeywordCounter.java
> +    public static String[] keywords = {"abstract", "continue", "for", "new", "switch",
явно где-то они описаны уже

2020-02-19 10:03 UTC, vadim-gleyf commented on unit3-4/src/main/java/java_parsers/in/JavaByteParser.java
> +    private static int comments = 0;
статик состояние плохо, код нечитабельный абсолютно, куча функций которых меняют его и читают


сделай норм метод который получает там лист строк и отдает сколько каких кейвордов, все вычисления должны быть внутри него

2020-02-19 10:03 UTC, vadim-gleyf commented on unit3-4/src/main/java/java_parsers/in/JavaByteParser.java
> +            String[] words = line
регуляркой лучше

2020-02-19 10:03 UTC, vadim-gleyf commented on unit3-4/src/main/java/java_parsers/in/JavaByteParser.java
> +        for (String key : result.keySet()) {
ентри сет ведь можно

+ поправляй все о чем говорит идея / сонар

про такие вещи сама среда разработки ведь подсказывает

2020-02-19 10:03 UTC, vadim-gleyf commented on unit3-4/src/main/java/java_parsers/in/JavaByteParser.java
> +    private static void parse(String[] words) {
очень высокая цикломатическая сложность

даже не смогу понять зачем все эти ифы и счетчики
+ дублирование кода из соседнего метода

2020-02-19 10:03 UTC, vadim-gleyf commented on unit3-4/src/main/java/java_parsers/JavaStringParser.java
> +        while (in.ready()) {
копипасты быть не должно

2020-02-19 10:03 UTC, vadim-gleyf commented on unit3-4/src/main/java/utf_converter/UtfConverter.java
> +            in.close();
может не закрыться ведь если что-то свалится

2020-02-19 10:03 UTC, vadim-gleyf commented on unit3-4/src/main/java/films/Main.java
> +        try {
сделай просто интерфейс чтобы видно было что это работает
+ с выводом что-то
FilmsCollection{collection = {Once upon a time in Hollywood=Once upon a time in Hollywood}}

2020-02-19 10:03 UTC, vadim-gleyf commented on unit3-4/src/main/java/films/Main.java
> +        try {
или просто чтобы по запуску main было понятно что можно и читать и сохранять в файл

2020-02-19 10:03 UTC, vadim-gleyf commented on unit3-4/src/main/java/films/FilmCollection.java
> +    private HashMap<String, Film> collection;
map а не hashMap

2020-02-19 10:03 UTC, vadim-gleyf commented on unit3-4/src/main/java/films/FilmCollection.java
> +    public static final String BASE_PATH = "/unit3-4/src/main/java/films/collection/film_collection.txt";
папки out нет - упадет

2020-02-23 15:53 UTC, vadim-gleyf requested changes
коммиты нормально называй, а не просто unit 3-4

скачай сонарлинт(плагин в идее) и проверяй им все файлы на простые кейсы
типа порядок модификаторов, стримы не закрываешь и тп, не хочу про такое

2020-02-23 15:53 UTC, vadim-hleif commented on unit3-4/src/main/java/java_parsers/KeywordCounter.java
> +    public static String[] keywords = {"abstract", "continue", "for", "new", "switch",
не поправил

2020-02-23 15:53 UTC, vadim-hleif commented on unit3-4/src/main/java/java_parsers/KeywordCounter.java
> +    public static Map<String, KeywordCounter> checkWords(String[] words, Map<String, KeywordCounter> result) {
сложность метода не пропала

зачем все эти ифы? 

пару строчек же должно быть

сплит
фильтер
коллект

2020-02-26 06:04 UTC, vadim-gleyf requested changes

2020-02-26 06:04 UTC, vadim-hleif commented on unit3-4/src/main/java/java_parsers/KeywordCounter.java
> +                .replaceAll("((['\"])(?:(?!\\2|\\\\).|\\\\.)*\\2)|\\/\\/[^\\n]*|\\/\\*(?:[^*]|\\*(?!\\/))*\\*\\/", "") //Удаляю все комментарии
исправляй регулярку

в ней кейворды есть, доки с мотри

не надо ручками все перечислять

2020-02-26 06:04 UTC, vadim-hleif commented on unit3-4/src/main/java/java_parsers/KeywordCounter.java
> +                .split("[\\s|\\(|=|,|\\)|;]")) //дроблю на слова
тоже самое

2020-02-26 06:04 UTC, vadim-hleif commented on unit3-4/src/main/java/java_parsers/in/JavaByteParser.java
> +                    .replaceAll("\\/\\/", " new new new new new new new new new new")
что это ?

2020-02-27 19:04 UTC, igRock commented on unit3-4/src/main/java/java_parsers/in/JavaByteParser.java
> +    private static int comments = 0;
Это просто старый файл, который я паршу

2020-02-27 19:05 UTC, igRock commented on unit3-4/src/main/java/java_parsers/in/JavaByteParser.java
> +                    .replaceAll("\\/\\/", " new new new new new new new new new new")
Это для проверки того, что комментарии не считаются за ключевые слова

2020-02-28 08:25 UTC, vadim-gleyf approved these changes

2020-02-28 08:28 UTC, merged